sudo: required
services:
  - docker

before_install:
  - echo -e "machine github.com\n  login $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" > ~/.netrc
  - git lfs pull
  - docker build -t anoop/react-ci .

script:
  - docker run anoop/react-ci npm run test -- --coverage
