sudo: required
services:
  - docker

before_install:
  - echo -e "machine github.com\n  login $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" > ~/.netrc
  - git lfs pull
  - docker build -t anoop/react-ci .

script:
  - docker run anoop/react-ci npm run test -- --coverage
