language: node_js
services:
  - docker

before_install:
  - echo -e "machine github.com\n  login $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" > ~/.netrc
  - git lfs pull
  - docker build -t anoop/react-ci .

script:
  - docker run anoop/react-ci npm run test -- --coverage
